services:
  db:
    image: mysql:8.0
    container_name: softline_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: SoftLineTeste
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/01_CreateDatabase.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - softline_net

  backend:
    build:
      context: ./backend/SoftLineTeste.Api
      dockerfile: Dockerfile
    container_name: softline_backend
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      JWT_KEY: ${JWT_KEY}
      DB_CONNECTION_STRING: server=db;port=3306;database=SoftLineTeste;user=${MYSQL_USER};password=${MYSQL_PASSWORD};
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - softline_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: softline_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - softline_net

volumes:
  db_data:

networks:
  softline_net:
    driver: bridge
