CREATE DATABASE IF NOT EXISTS SoftLineTeste
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE SoftLineTeste;

CREATE TABLE IF NOT EXISTS Usuarios (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(500) NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Produtos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Codigo INT NOT NULL UNIQUE,
    Descricao VARCHAR(60) NOT NULL,
    CodigoBarras VARCHAR(14) NOT NULL,
    ValorVenda DECIMAL(18,2) NOT NULL,
    PesoBruto DECIMAL(18,3) NOT NULL,
    PesoLiquido DECIMAL(18,3) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Clientes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Codigo INT NOT NULL UNIQUE,
    Nome VARCHAR(60) NOT NULL,
    Fantasia VARCHAR(100) NOT NULL,
    Documento VARCHAR(20) NOT NULL,
    Endereco TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
